config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "profile", to: "user_projects#index"
  resources :projects, except: [:index] do
    # Resources of pages to get the methods for rendering async charts.
    resources :pages, only: [] do
      collection do
        get 'tasks_status'
        get 'user_tasks'
        get 'completed_tasks_by_day'
      end
    end
    # Get the performance page of a specific project.
    get "performance", to: "pages#performance"
    # Create an invitation for a user to join your project.
    post "user_projects", to: "user_projects#create"
    resources :user_projects, only: [] do
      patch :accept
      patch :decline
    end
    post "/projects/:project_id/tasks", to: "tasks#create", as: :task_create
    resources :tasks
    resources :tickets do
      resources :comments
    end
    member do
      patch "/tasks/:task_id/set_status", to: "tasks#set_status", as: :set_task_status
    end
    # Chatroom
    resources :chatrooms, only: :show do
      # Messages
      resources :messages, only: :create
    end
  end


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/project.rb
class Project < ApplicationRecord
  has_one :chatroom, class_name: "chatroom", foreign_key: "chatroom_id"
  has_many :user_projects, dependent: :destroy
  has_many :tasks, dependent: :destroy
  has_many :tickets, dependent: :destroy
  has_rich_text :content
  has_many_attached :photos
  belongs_to :user
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def show
    # @users will be an array of all the users related to this project.
    @users = []
    @project = Project.find(params[:id])
    @tasks = Task.where("project_id = ?", @project.id)
    # Get all the user_projects who have an invitation with the status accepted and an project_id of this project.
    @users_assigned_to_project = UserProject.where(["project_id = ? and invitation_accepted = ?", @project.id, true])
    # Loop and find the users through the user_id and push them into the @users array
    @users_assigned_to_project.each do |user_project|
      @users << User.find(user_project.user_id)
    end
    # Find the user who created the project and push them to the array aswell. Because
    # you want to be able to select them to a task.
    @users << @project_owner = User.find(@project.user_id)
    @new_task = Task.new
    @new_user_project = UserProject.new
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    @project.user_id = current_user.id
    @project.chatroom_id = Chatroom.create(name: @project.name).id

    if @project.save
      redirect_to project_path(@project.id), notice: 'Project successfully created.'
    else
      render :new, status: :unprocessable_entity, notice: 'We were not able to create a new project.'
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    @project.update(project_params)
    redirect_to project_path(@project)
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to profile_path
  end

  private

  def project_params
    params.require(:project).permit(:name, :content, photos: [])
  end
end

app/views/projects/shared/_add_user_modal.html.erb
<div class="modal fade" id="addUsersModal" tabindex="-1" aria-labelledby="addUsersModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="addUsersModalLabel">Add User</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= simple_form_for [@project,@new_user_project] do |f| %>
          <%= simple_fields_for :other do |o| %>
            <%= o.input :email%>
          <% end %>
          <%= f.input :project_id, :as => :hidden, :input_html => { :value => @project.id }%>
          <%= button_to "Send Invite", project_user_projects_path(@project), id:"add-users-button"%>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/projects/shared/_edit_task_modal.html.erb
    <!-- TASK EDIT MODAL -->
  <div class="modal fade" id="editModal" tabindex="-1" aria-labelledby="editModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="editModalLabel">New Task</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <%= simple_form_for [@project,task] do |f| %>
            <%= f.input :title %>
            <%= f.input :description, :as => :text, :input_html => { 'rows' => 5, 'cols' => 10 } %>
            <%= f.input :priority, collection: ["Critical","High","Medium", "Low" ]  %>
            <%= f.input :status, collection: ["To Discuss","Unassigned","To-Do", "In progress", "Completed" ] %>
            <%= f.input :user_id,
            collection: @users.map{|user| [user.id, "#{user.first_name} #{user.last_name}"]},
            value_method: :first,
            label_method: :second
            %>
            <%= f.input :project_id, :as => :hidden, :input_html => { :value => @project.id }%>
            <%= button_to "Update Task", edit_project_task_path(@project), id:"btn-update-task", method: :put %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

app/views/projects/shared/_task.html.erb
<div class="task priority-<%= task.priority.downcase%>" id="<%= set_task_status_project_url(task_id: task.id, id: @project.id) %>" >
  <em style="margin:0; max-width:150px;white-space:initial;"><%= task.title%></em>
    <% task_user = User.find(task.user_id)%>
    <%if task_user.photo.attached?%>
        <%= cl_image_tag task_user.photo.key, class:"avatar", crop: :fill %>
    <% else %>
      <img class="avatar" style="height:50px; width:50px;" src="https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png">
    <% end %>
</div>

app/views/projects/shared/_task_modal.html.erb
<div class="modal fade" id="task<%=task.id%>Modal" tabindex="-1" aria-labelledby="task<%=task.id%>ModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content tag-<%=task.priority.downcase%>">
      <div class="modal-header">
        <h3 class="modal-title" id="task<%=task.id%>ModalLabel"><%=task.title%>  <span class="tag-<%=task.priority.downcase%>"><i class="fa-solid fa-circle"></i> <%=task.priority%></span></h3>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p><strong>Description: </strong><%=task.description%></p>
        <div style="display:flex;align-items:center;">
          <h6 style="margin-right:20px;margin-bottom:0px;"><strong style="margin-right:10px;">Assigned to:</strong> <%= User.find(task.user_id).first_name%> <%= User.find(task.user_id).last_name%></h6>
          <% task_user = User.find(task.user_id)%>
          <%if task_user.photo.attached?%>
            <%= cl_image_tag task_user.photo.key, class:"avatar", crop: :fill %>
          <% else %>
            <img class="avatar" src="https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png">
          <% end %>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" id = "edit-task" data-bs-toggle="modal" data-bs-target="#editModal"><i class="fa-solid fa-pen-to-square"></i></button>
        <%= link_to project_task_path(task.id, id: @project.id), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
          <i class="fa-solid fa-trash" id="delete-task"></i>
        <%end%>
      </div>
    </div>
  </div>
</div>

app/views/projects/shared/_task_modal_without_user.html.erb
<div class="modal fade" id="task<%=task.id%>Modal" tabindex="-1" aria-labelledby="task<%=task.id%>ModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content tag-<%=task.priority.downcase%>">
      <div class="modal-header">
        <h3 class="modal-title" id="task<%=task.id%>ModalLabel"><%=task.title%>  <span class="tag-<%=task.priority.downcase%>"><i class="fa-solid fa-circle"></i> <%=task.priority%></span></h3>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p><strong>Description: </strong><%=task.description%></p>
      </div>
      <div class="modal-footer">
        <button type="button" id = "edit-task" data-bs-toggle="modal" data-bs-target="#editModal"><i class="fa-solid fa-pen-to-square"></i></button>
        <%= link_to project_task_path(task.id, id: @project.id), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
          <i class="fa-solid fa-trash" id="delete-task"></i>
        <%end%>
      </div>
    </div>
  </div>
</div>

app/views/projects/shared/_task_without_user.html.erb
<div class="task priority-<%= task.priority.downcase%>" id="<%= set_task_status_project_url(task_id: task.id, id: @project.id) %>" >
  <em style="margin:0; max-width:150px;white-space:initial;"><%= task.title%></em>
    <% task_user = User.find(task.user_id)%>
</div>