config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "profile", to: "user_projects#index"
  resources :projects, except: [:index] do
    # Resources of pages to get the methods for rendering async charts.
    resources :pages, only: [] do
      collection do
        get 'tasks_status'
        get 'user_tasks'
        get 'completed_tasks_by_day'
      end
    end
    # Get the performance page of a specific project.
    get "performance", to: "pages#performance"
    # Create an invitation for a user to join your project.
    post "user_projects", to: "user_projects#create"
    resources :user_projects, only: [] do
      patch :accept
      patch :decline
    end
    post "/projects/:project_id/tasks", to: "tasks#create", as: :task_create
    resources :tasks
    resources :tickets do
      resources :comments
    end
    member do
      patch "/tasks/:task_id/set_status", to: "tasks#set_status", as: :set_task_status
    end
    # Chatroom
    resources :chatrooms, only: :show do
      # Messages
      resources :messages, only: :create
    end
  end


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/user_project.rb
class UserProject < ApplicationRecord
  belongs_to :user
  belongs_to :project
end

app/controllers/user_projects_controller.rb
class UserProjectsController < ApplicationController
  def index
    @projects = Project.where("user_id = ?", current_user.id)
    @participating_projects = UserProject.where(["user_id = ? AND invitation_accepted = ?", current_user.id, true])
    @invitations = UserProject.where(["user_id = ? AND invitation_accepted = ?", current_user.id, false])
  end

  def create
    @user = User.find_by("email = ? ", params[:other][:email])
    @project = Project.find(params[:project_id])
    @user_project = UserProject.new(user_id: @user.id, project_id: @project.id)
    @user_project.invitation_accepted = false

    if @user_project.save
      redirect_to project_path(@project), notice: 'User successfully invited.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def accept
    @user_project = UserProject.find(params[:user_project_id])
    @user_project.invitation_accepted = true

    redirect_to project_path(params[:project_id]) if @user_project.save
  end

  def decline
    @user_project = UserProject.find(params[:user_project_id])
    @user_project.destroy
    redirect_to profile_path
  end
end

app/views/user_projects/index.html.erb
<div class="profile-page d-flex justify-content-between">
  <div class="profile-card text-center" style="position: -webkit-sticky; position: sticky; top: var(--navigation-bar-offset, 20px) !important;">
    <div class="id-info d-flex justify-content-between" data-controller="modal">
      <div class="img-profile">
      <!-- Profile Picture From User -->
        <button type="button" class="icon-button" data-bs-toggle="modal" data-bs-target="#invitationsModal">
        <%if current_user.photo.attached?%>
          <%= cl_image_tag current_user.photo.key, class:"avatar material-icons", crop: :fill %>
        <% else %>
          <img class="avatar material-icons" src="https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png">
        <% end %>
        <span class="icon-button__badge"><%= @invitations.count%></span>
        </button>
      </div>
      <div class="users-info">
        <h3 style="text-align:left;">Hello <%= current_user.first_name %>! </h3>
        <p> <%= current_user.email %> </p>
      </div>
    </div>
    <div class="user-record text-center">
      <p class="text-center" style="color:gray">Your info:</p>
      <div class="my-info text-center">
        <p style="text-align:start;"> <%= current_user.information %> </p>
      </div>
      <a class="btn text-center" type="button" href="/users/edit">Update Profile</a>
    </div>
  </div>
  <div class="profile-items">
    <div class="categories-row d-flex justify-content-between" style="position: -webkit-sticky; position: sticky; top: var(--navigation-bar-offset, 0px) !important;">
      <p class="1" style="margin-left:25px;">Project</p>
      <p class="2" style="margin-right:15px; margin-left:15px;">Your Role</p>
      <p class="3" style="margin-right:15px;">Status</p>
    </div>
    <div class="info-row">
        <!-- Div for project information. -->
        <% @projects.each do |project|%>
          <%= link_to project_path(project), style: "text-decoration:none;", data: { turbo: false } do %>
            <div class="btn-table table-info d-flex justify-content-between text-center my-5" >
              <!-- Project Owner Photo -->
              <% project_user = User.find(project.user_id) %>
              <p style="width:120px; margin-top:15px;"><%= project.name%></p>
              <p style="width:120px; margin-top:15px;">Manager</p>
              <p style="width:120px; margin-top:15px;">On Going</p>
            </div>
          <% end %>
        <% end %>
        <!-- Div for project information. -->
    </div>

    <div class="info-row">
      <!-- Div for project information. -->
      <% @participating_projects.each do |participation|%>
        <% project = Project.find(participation.project_id) %>

          <%= link_to project_path(project), style: "text-decoration:none;", data: { turbo: false } do %>
          <div class="btn-table table-info d-flex justify-content-between text-center my-5" >
            <p style="width:120px; margin-top:15px;"><%= project.name%></p>
            <p style="width:120px; margin-top:15px;">Developer</p>
            <p style="width:120px; margin-top:15px;">On Going</p>
          </div>
        <% end %>
      <% end %>
        <!-- Div for project information. -->
    </div>
    <%= link_to "Create new Project", new_project_path, class:"create-project btn" %>
  </div>
</div>


<!-- Modal to accept decline Invitation for projects -->
        <div class="modal fade" id="invitationsModal" tabindex="-1" aria-labelledby="invitationsModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content" style="width:700px">
              <div class="modal-header">
                <h1 class="modal-title fs-5" id="invitationsModalLabel">Invitations</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                <% @invitations.each do |invitation|%>
                  <% project = Project.find(invitation.project_id)%>
                  <div style="display:flex;">
                    <p><strong><%= User.find(project.user_id).first_name%> <%= User.find(project.user_id).last_name%></strong> invited you to: <%= Project.find(invitation.project_id).name%><p>
                    <div style="display:flex;margin-left:auto;">
                    <%= button_to "Accept", project_user_project_accept_path(invitation.project_id, invitation),id:"accept-button", method: :patch %>
                    <%= button_to "Decline", project_user_project_decline_path(invitation.project_id, invitation),id:"decline-button", method: :patch %>
                    </div>
                  </div>
                <%end%>
              </div>
            </div>
          </div>
        </div>
<!-- Modal to accept decline Invitation for projects -->