config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "profile", to: "user_projects#index"
  resources :projects, except: [:index] do
    # Resources of pages to get the methods for rendering async charts.
    resources :pages, only: [] do
      collection do
        get 'tasks_status'
        get 'user_tasks'
        get 'completed_tasks_by_day'
      end
    end
    # Get the performance page of a specific project.
    get "performance", to: "pages#performance"
    # Create an invitation for a user to join your project.
    post "user_projects", to: "user_projects#create"
    resources :user_projects, only: [] do
      patch :accept
      patch :decline
    end
    post "/projects/:project_id/tasks", to: "tasks#create", as: :task_create
    resources :tasks
    resources :tickets do
      resources :comments
    end
    member do
      patch "/tasks/:task_id/set_status", to: "tasks#set_status", as: :set_task_status
    end
    # Chatroom
    resources :chatrooms, only: :show do
      # Messages
      resources :messages, only: :create
    end
  end


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/project.rb
class Project < ApplicationRecord
  has_one :chatroom, class_name: "chatroom", foreign_key: "chatroom_id"
  has_many :user_projects, dependent: :destroy
  has_many :tasks, dependent: :destroy
  has_many :tickets, dependent: :destroy
  has_rich_text :content
  has_many_attached :photos
  belongs_to :user
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def show
    # @users will be an array of all the users related to this project.
    @users = []
    @project = Project.find(params[:id])
    @tasks = Task.where("project_id = ?", @project.id)
    # Get all the user_projects who have an invitation with the status accepted and an project_id of this project.
    @users_assigned_to_project = UserProject.where(["project_id = ? and invitation_accepted = ?", @project.id, true])
    # Loop and find the users through the user_id and push them into the @users array
    @users_assigned_to_project.each do |user_project|
      @users << User.find(user_project.user_id)
    end
    # Find the user who created the project and push them to the array aswell. Because
    # you want to be able to select them to a task.
    @users << @project_owner = User.find(@project.user_id)
    @new_task = Task.new
    @new_user_project = UserProject.new
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    @project.user_id = current_user.id
    @project.chatroom_id = Chatroom.create(name: @project.name).id

    if @project.save
      redirect_to project_path(@project.id), notice: 'Project successfully created.'
    else
      render :new, status: :unprocessable_entity, notice: 'We were not able to create a new project.'
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    @project.update(project_params)
    redirect_to project_path(@project)
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to profile_path
  end

  private

  def project_params
    params.require(:project).permit(:name, :content, photos: [])
  end
end

app/views/projects/edit.html.erb
<div class="edit-card my-4">
  <h2 class='text-center'>Update Project</h2>

  <%= simple_form_for @project do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <div class="field">
        <%= f.input :name,
                    required: true,
                    autofocus: true,
                    input_html: { autocomplete: "name" }%>
        <%= f.rich_text_area :content,
                    required: true,
                    autofocus: true,
                    input_html: { autocomplete: "description" }%>
        <%= f.input :photos,
                    required: false,
                    autofocus: true,
                    as: :file, input_html: { multiple: true } %>
        <p><small>Max of 10M</small><p>
      </div>
    </div>
    <div class="form-actions text-center">
      <input class="btn-log-in" type="submit" href="/profile" value="Update Project">
    </div>
  <% end %>
</div>

app/views/projects/new.html.erb
<div class="edit-card my-4">
  <h2 class='text-center'>New Project</h2>

  <%= simple_form_for @project do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <div class="field">
        <%= f.input :name,
                    required: true,
                    autofocus: true,
                    input_html: { autocomplete: "name" }%>
        <%= f.rich_text_area :content,
                    required: true,
                    autofocus: true,
                    input_html: { autocomplete: "description" }%>
        <%= f.input :photos,
                    required: false,
                    autofocus: true,
                    as: :file, input_html: { multiple: true } %>
        <p><small>Upload project wireframes. Max of 10MB.</small><p>
      </div>
    </div>
    <div class="form-actions text-center">
      <input class="btn-log-in" type="submit" href="/profile" value="Create Project">
    </div>
  <% end %>
</div>

app/views/projects/show.html.erb
<!-- Div for the product description and carousel with project pictures. -->
  <button type="button" class="btn btn-warning" id="toggle-btn">Project Details <i class="fa-solid fa-arrow-down"></i></button>
<div>
  <div id="toggle-example">
    <div class="product-banner" data-controller="modal" style= "box-shadow: rgb(99 99 99 / 20%) 0px 2px 8px 0px;">
      <div style="width:40%;">
        <div style="display:flex; justify-content:center;margin-bottom:20px;width:500px;align-items:center">
          <!-- Project Owner Photo.-->
          <% project_user = User.find(@project.user_id)%>
          <h1 style="word-break: break-word;margin-right:100px;"><%= @project.name%></h1>
        </div>
        <div style="word-break:break-word">
          <%= @project.content %>
        </div>
          <!-- USER AVATAR CAROUSEL -->
        <div class="avatar-carousel">
          <div class="wrapper">
            <button class="prev" id="prevSlide" type="button">➤</button>
            <div class="slider">
              <% @users.each_with_index do |user, index| %>
                <% if user.photo.attached? %>
                  <div class="item">
                    <%= cl_image_tag user.photo.key, class:"avatar", style:"height:50px; width:50px;", crop: :fill %>
                    <div class="title"><%= user.first_name%> <%= user.last_name%></div>
                  </div>
                <% else%>
                  <div class="item">
                    <img class="avatar" style="height:50px; width:50px;" src="https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png">
                    <div class="title"><%= user.first_name%> <%= user.last_name%></div>
                  </div>
                <% end %>
              <% end %>
            </div>
            <button class="next" id="nextSlide" type="button">➤</button>
          </div>
          <button type="button" style="margin-left:20%" id="add-users" class="btn" data-bs-toggle="modal" data-bs-target="#addUsersModal" data-bs-whatever="@mdo">Add Users</button></strong>
        </div>
  <!-- USER AVATAR CAROUSEL -->
      </div>
      <div id="carousel-<%= @project.id%>" class="carousel slide" data-bs-ride="carousel" style="width:40%;">
        <div class="carousel-inner" style="border-radius:20px;">
          <!-- Check if the project has attached photos -->
          <% if @project.photos.attached? %>
            <!-- Loop through the project photos -->
            <% @project.photos.each_with_index do |photo, index|%>
              <!-- If the index is one then the class has to be active. -->
              <% if index == 0 %>
                <div class="carousel-item active">
                  <%= cl_image_tag photo.key, height: 325, style:"border-radius:20px;", crop: :fill %>
                </div>
              <% else %>
                <div class="carousel-item ">
                  <%= cl_image_tag photo.key, height: 325, style:"border-radius:20px;", crop: :fill %>
                </div>
              <% end %>
            <% end %>
          <%else%>
          <!-- If the project does not have photos attached render 3 random photos -->
            <div class="carousel-item active">
              <img src="https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2940&q=80" class="d-block w-100" alt="..." style="height:325px;border-radius:20px;">
            </div>
            <div class="carousel-item">
              <img src="https://images.unsplash.com/photo-1552664730-d307ca884978?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80" class="d-block w-100" alt="..." style="height: 325px;border-radius:20px;">
            </div>
            <div class="carousel-item">
              <img src="https://images.unsplash.com/photo-1556761175-b413da4baf72?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1974&q=80" class="d-block w-100" alt="..." style="height: 325px;border-radius:20px;">
            </div>
          <%end%>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carousel-<%= @project.id%>" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carousel-<%= @project.id%>" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>
      <!-- MODAL ADD USERS  -->
      <%= render "projects/shared/add_user_modal" %>
      <!-- MODAL ADD USERS  -->
      <% if @project.user_id == current_user.id %>
            <div class="project-actions">
                <%= link_to project_path(@project), class:"btn-action", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
                  <i class="fa-solid fa-trash fa-lg"></i>
                <%end%>
                <%= link_to edit_project_path(@project), class:"btn-action" do %>
                  <i class="fa-solid fa-pen-to-square fa-lg"></i>
                <%end%>
            </div>
          <% end %>
    </div>
  </div>



  <div class="board" data-controller="sortable modal" style="margin-top: 9%;">
    <div class="kanban-block text-center">
      <div class="board-title">
        <p><strong>To Discuss</strong></p>
        <button type="button" class="add-task" data-bs-toggle="modal" data-bs-target="#formModal" data-bs-whatever="@mdo"><i class="fa-solid fa-plus"></i></button>
      </div>
      <div id="todiscuss" data-sortable-target="todiscuss" style="margin-top:20px">
        <% @tasks.each do |task|%>
          <% if task.status == "To Discuss"%>
            <a id="link" data-bs-toggle="modal" data-bs-target="#task<%=task.id%>Modal"><%= render "projects/shared/task_without_user", task: task %></a>
            <%= render "projects/shared/task_modal_without_user", task: task %>
            <%= render "projects/shared/edit_task_modal", task: task %>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="kanban-block text-center" >
      <div class="board-title">
        <p><strong>Unassigned</strong></p>
        <button type="button" class="add-task" data-bs-toggle="modal" data-bs-target="#formModal" data-bs-whatever="@mdo"><i class="fa-solid fa-plus"></i></button>
      </div>
      <div id="unassigned" data-sortable-target="unassigned" style="margin-top:20px">
        <% @tasks.each do |task|%>
          <% if task.status == "Unassigned"%>
            <a id="link" data-bs-toggle="modal" data-bs-target="#task<%=task.id%>Modal"><%= render "projects/shared/task_without_user", task: task %></a>
            <%= render "projects/shared/task_modal_without_user", task: task %>
            <%= render "projects/shared/edit_task_modal", task: task %>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="kanban-block text-center" >
      <div class="board-title">
        <p><strong>To-Do</strong></p>
        <button type="button" class="add-task" data-bs-toggle="modal" data-bs-target="#formModal" data-bs-whatever="@mdo"><i class="fa-solid fa-plus"></i></button>
      </div>
      <div id="todo" data-sortable-target="todo" style="margin-top:20px" >
        <% @tasks.each do |task|%>
          <% if task.status == "To-Do"%>
            <a id="link" data-bs-toggle="modal" data-bs-target="#task<%=task.id%>Modal"><%= render "projects/shared/task", task: task %></a>
            <%= render "projects/shared/task_modal", task: task %>
            <%= render "projects/shared/edit_task_modal", task: task %>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="kanban-block text-center" >
      <div class="board-title">
        <p><strong>In Progress</strong></p>
        <button type="button" class="add-task" data-bs-toggle="modal" data-bs-target="#formModal" data-bs-whatever="@mdo"><i class="fa-solid fa-plus"></i></button>
      </div>
      <div id="inprogress" data-sortable-target="inprogress" style="margin-top:20px">
        <% @tasks.each do |task|%>
          <% if task.status == "In progress"%>
            <a id="link" data-bs-toggle="modal" data-bs-target="#task<%=task.id%>Modal"><%= render "projects/shared/task", task: task %></a>
            <%= render "projects/shared/task_modal", task: task %>
            <%= render "projects/shared/edit_task_modal", task: task %>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="kanban-block text-center" >
      <div class="board-title">
        <p><strong>Completed</strong></p>
        <button type="button" class="add-task" data-bs-toggle="modal" data-bs-target="#formModal" data-bs-whatever="@mdo"><i class="fa-solid fa-plus"></i></button>
      </div>
      <div id="completed" data-sortable-target="completed" style="margin-top:20px">
        <% @tasks.each do |task|%>
          <% if task.status == "Completed"%>
            <a id="link" data-bs-toggle="modal" data-bs-target="#task<%=task.id%>Modal"><%= render "projects/shared/task", task: task %></a>
            <%= render "projects/shared/task_modal", task: task %>
            <%= render "projects/shared/edit_task_modal", task: task %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
  <!-- MODAL FORM  -->
  <div class="modal fade" id="formModal" tabindex="-1" aria-labelledby="formModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="formModalLabel">New Task</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <%= simple_form_for [@project,@new_task] do |f| %>
            <%= f.input :title %>
            <%= f.input :description, :as => :text, :input_html => { 'rows' => 5, 'cols' => 10 } %>
            <%= f.input :priority, collection: ["Critical","High","Medium", "Low" ]  %>
            <%= f.input :status, collection: ["To Discuss","Unassigned","To-Do", "In progress", "Completed" ] %>
            <%= f.input :user_id,
            collection: @users.map{|user| [user.id, "#{user.first_name} #{user.last_name}"]},
            value_method: :first,
            label_method: :second
            %>
            <%= f.input :project_id, :as => :hidden, :input_html => { :value => @project.id }%>
            <%= button_to "Create Task", project_task_create_path(@project), id:"btn-create-task"%>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <!-- MODAL FORM  -->

  <!-- MODAL TASK  -->
  <div class="modal fade" id="task1Modal" tabindex="-1" aria-labelledby="task1ModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="task1ModalLabel">Task 1</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <h1>Information about the task</h1>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary">Send message</button>
        </div>
      </div>
    </div>
  </div>
  <!-- MODAL TASK  -->


  <!-- MODAL ADD USERS  -->
  <div class="modal fade" id="addUsersModal" tabindex="-1" aria-labelledby="addUsersModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="addUsersModalLabel">Add User</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <%= simple_form_for [@project,@new_user_project] do |f| %>
            <%= f.input :user_id %>
            <%= f.input :project_id, :as => :hidden, :input_html => { :value => @project.id }%>
            <%= button_to "Add User", project_user_projects_path(@project)%>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <!-- MODAL ADD USERS  -->
</div>